### ISSUE TITLE
no paths found and throwing runtime error

### ISSUE THREAD

**Issue by JOJ0** [AdamGagorik/pyrename#1]
Not sure if you are still using this tool and are willing to maintain it. I was looking for a simple python based tool that renames files based on python re. This looked promising. Can't be wrong much I guess. Anyway, this is what happens when I try to use the simple example from your README.md - file in the dir are nothing special, it's the same result with other directories:

```
$ ls
R06 CH1.wav  R06 CH2.wav  R06 K.wav    R06 OH.wav   R06 Rm.wav   R06 Sn.wav   R06 TmHi.wav R06 TmLo.wav SM Cl.wav    SM K07.wav   SM Rm.wav
```

```
~/somedir $ pyrename  '(.*)\.py' '\g<1>_renamed.py'
[2021-02-27 08:54:34][42649][INFO ]: pattern    = (.*)\.py
[2021-02-27 08:54:34][42649][INFO ]: replace    = \g<1>_renamed.py
[2021-02-27 08:54:34][42649][INFO ]: nomatch    = None
[2021-02-27 08:54:34][42649][INFO ]: exclude[0] = options.py
[2021-02-27 08:54:34][42649][INFO ]: top        = /Users/jojo/somedir
[2021-02-27 08:54:34][42649][INFO ]: recursive  = False
[2021-02-27 08:54:34][42649][INFO ]: dirs       = False
[2021-02-27 08:54:34][42649][INFO ]: both       = False
[2021-02-27 08:54:34][42649][INFO ]: force      = False
[2021-02-27 08:54:34][42649][INFO ]: git        = False
[2021-02-27 08:54:34][42649][INFO ]: ignorecase = False
[2021-02-27 08:54:34][42649][INFO ]: silent     = False
[2021-02-27 08:54:34][42649][INFO ]: func       = False
[2021-02-27 08:54:34][42649][INFO ]: 0 old
[2021-02-27 08:54:34][42649][INFO ]: 0 old (unique)
[2021-02-27 08:54:34][42649][INFO ]: 0 new
[2021-02-27 08:54:34][42649][INFO ]: 0 new (unique)
[2021-02-27 08:54:34][42649][INFO ]: 0 same
[2021-02-27 08:54:34][42649][ERROR]: no old paths found
[2021-02-27 08:54:34][42649][ERROR]: no new paths found
[2021-02-27 08:54:34][42649][ERROR]: caught unhandled exception
Traceback (most recent call last):
  File "/Users/jojo/git/pyrename/pyrename/apps/main.py", line 167, in <module>
    main()
  File "/Users/jojo/git/pyrename/pyrename/apps/main.py", line 155, in main
    raise RuntimeError('invalid configuration')
RuntimeError: invalid configuration
```

How could I further debug? What does the paths error mean? In my case I would like to stay in the same directory and just rename a bunch of files and only touch the filename, not move to other directory or something.

Maybe you can point me in the right direction. Thanks a ton!
Jojo

**Comment by JOJ0** [comment]
Well, my bad, I was to stupid to change the ending in the example from .py to .wav. all good now. I'll close this once I get results.

**Comment by JOJ0** [comment]
Thanks againg for this tool. I thought something terrible happened when the exception occured before I even realized that it was "user error" ;-) I sent you this PR to make it look not as terrible when just a regex doesn't match: #2. Closing this one!
